# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofx_accountID', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('overdraft', models.FloatField()),
                ('balance', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OFX_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('ofx_file', models.FileField(upload_to='ofx_uploads/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ofx_txID', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField(blank=True, default=0)),
                ('ofx_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.OFX_Upload')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofx_type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='typeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction_Type'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Bank'),
        ),
    ]
