# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20170113_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofx_upload',
            old_name='accountID',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ofx_txID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
