# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20170113_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofx_upload',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Account'),
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='period_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='period_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
