# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20170123_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_location', models.FileField(upload_to='uploaded_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ofx_upload',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Account'),
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='ofx_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Uploaded_File'),
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='period_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='period_start',
            field=models.DateTimeField(),
        ),
    ]
