# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170123_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofx_upload',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ofx_upload',
            name='period_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
