# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20170123_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='overdraft',
            field=models.FloatField(default=0),
        ),
    ]
