# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_type',
            name='ofx_type',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
